In [2]:
import pandas as pd
import numpy as np
from sklearn import  preprocessing, model_selection
import matplotlib.pyplot as plt

# read the csv file into our data variable
data = pd.read_csv('breast-cancer.csv')

# delete the unwanted id column
data.drop(['id'], 1, inplace=True)

# make up for missing entries
data.replace('?', -9999, inplace=True)

# get our attributes and classes in place
X = np.array(data.drop(['class'], 1))
y = np.array(data['class'])

# split data into training and testing sections

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = model_selection.train_test_split(X, y, test_size=0.2)
#feature dataset into tranig set and test set:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)
# fitting naive bayes ti the traning test:
 
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()
model.fit(X_train,y_train)

#predicting test set results:
y_pred = model.predict(X_test)
y_pred







array([2, 2, 2, 4, 4, 2, 2, 2, 2, 4, 2, 4, 4, 2, 2, 2, 2, 2, 2, 2, 2, 4,
       2, 2, 4, 4, 4, 2, 2, 2, 2, 4, 4, 4, 4, 2, 2, 2, 2, 2, 4, 2, 4, 2,
       2, 4, 4, 2, 2, 2, 2, 2, 2, 4, 2, 4, 4, 4, 2, 2, 2, 2, 2, 2, 2, 4,
       2, 2, 4, 4, 2, 4, 2, 4, 2, 2, 2, 2, 2, 4, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 4, 2, 2, 4, 2, 4, 2, 4, 2, 4, 4, 2, 2, 2, 2, 2, 2,
       2, 4, 2, 4, 4, 2, 4, 4, 2, 4, 2, 4, 2, 4, 4, 2, 2, 2, 4, 4, 4, 4,
       2, 2, 4, 2, 2, 4, 2, 4], dtype=int64)

In [3]:
#making confusion matrix:


from sklearn.metrics import confusion_matrix,classification_report
cm  = confusion_matrix(y_test,y_pred)
print(cm)
print( classification_report(y_test, y_pred))

[[91  6]
 [ 0 43]]
              precision    recall  f1-score   support

           2       1.00      0.94      0.97        97
           4       0.88      1.00      0.93        43

    accuracy                           0.96       140
   macro avg       0.94      0.97      0.95       140
weighted avg       0.96      0.96      0.96       140



In [4]:
accuracy =model.score(X_test,y_test)
accuracy

0.9571428571428572

In [5]:
X_test[0:10]
y_test[0:10]
model.predict(X_test[0:10])
model.predict_proba(X_test[:10])
from sklearn.model_selection import cross_val_score

cross_val_score(GaussianNB(),X_train, y_train, cv=5)

array([0.92857143, 0.97321429, 0.9375    , 0.96428571, 0.94594595])